// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/wctzpb.proto

#ifndef PROTOBUF_INCLUDED_src_2fwctzpb_2eproto
#define PROTOBUF_INCLUDED_src_2fwctzpb_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3006001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/any.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_src_2fwctzpb_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_src_2fwctzpb_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[14]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_src_2fwctzpb_2eproto();
namespace wctzpb {
class BinRangeList;
class BinRangeListDefaultTypeInternal;
extern BinRangeListDefaultTypeInternal _BinRangeList_default_instance_;
class ChannelMasks;
class ChannelMasksDefaultTypeInternal;
extern ChannelMasksDefaultTypeInternal _ChannelMasks_default_instance_;
class ChannelMasks_BinRangeListsEntry_DoNotUse;
class ChannelMasks_BinRangeListsEntry_DoNotUseDefaultTypeInternal;
extern ChannelMasks_BinRangeListsEntry_DoNotUseDefaultTypeInternal _ChannelMasks_BinRangeListsEntry_DoNotUse_default_instance_;
class Depo;
class DepoDefaultTypeInternal;
extern DepoDefaultTypeInternal _Depo_default_instance_;
class DepoSet;
class DepoSetDefaultTypeInternal;
extern DepoSetDefaultTypeInternal _DepoSet_default_instance_;
class FloatArray;
class FloatArrayDefaultTypeInternal;
extern FloatArrayDefaultTypeInternal _FloatArray_default_instance_;
class Frame;
class FrameDefaultTypeInternal;
extern FrameDefaultTypeInternal _Frame_default_instance_;
class Frame_ChannelMasksEntry_DoNotUse;
class Frame_ChannelMasksEntry_DoNotUseDefaultTypeInternal;
extern Frame_ChannelMasksEntry_DoNotUseDefaultTypeInternal _Frame_ChannelMasksEntry_DoNotUse_default_instance_;
class Frame_TaggedTracesEntry_DoNotUse;
class Frame_TaggedTracesEntry_DoNotUseDefaultTypeInternal;
extern Frame_TaggedTracesEntry_DoNotUseDefaultTypeInternal _Frame_TaggedTracesEntry_DoNotUse_default_instance_;
class Frame_TraceSummariesEntry_DoNotUse;
class Frame_TraceSummariesEntry_DoNotUseDefaultTypeInternal;
extern Frame_TraceSummariesEntry_DoNotUseDefaultTypeInternal _Frame_TraceSummariesEntry_DoNotUse_default_instance_;
class IntArray;
class IntArrayDefaultTypeInternal;
extern IntArrayDefaultTypeInternal _IntArray_default_instance_;
class Payload;
class PayloadDefaultTypeInternal;
extern PayloadDefaultTypeInternal _Payload_default_instance_;
class Point;
class PointDefaultTypeInternal;
extern PointDefaultTypeInternal _Point_default_instance_;
class Trace;
class TraceDefaultTypeInternal;
extern TraceDefaultTypeInternal _Trace_default_instance_;
}  // namespace wctzpb
namespace google {
namespace protobuf {
template<> ::wctzpb::BinRangeList* Arena::CreateMaybeMessage<::wctzpb::BinRangeList>(Arena*);
template<> ::wctzpb::ChannelMasks* Arena::CreateMaybeMessage<::wctzpb::ChannelMasks>(Arena*);
template<> ::wctzpb::ChannelMasks_BinRangeListsEntry_DoNotUse* Arena::CreateMaybeMessage<::wctzpb::ChannelMasks_BinRangeListsEntry_DoNotUse>(Arena*);
template<> ::wctzpb::Depo* Arena::CreateMaybeMessage<::wctzpb::Depo>(Arena*);
template<> ::wctzpb::DepoSet* Arena::CreateMaybeMessage<::wctzpb::DepoSet>(Arena*);
template<> ::wctzpb::FloatArray* Arena::CreateMaybeMessage<::wctzpb::FloatArray>(Arena*);
template<> ::wctzpb::Frame* Arena::CreateMaybeMessage<::wctzpb::Frame>(Arena*);
template<> ::wctzpb::Frame_ChannelMasksEntry_DoNotUse* Arena::CreateMaybeMessage<::wctzpb::Frame_ChannelMasksEntry_DoNotUse>(Arena*);
template<> ::wctzpb::Frame_TaggedTracesEntry_DoNotUse* Arena::CreateMaybeMessage<::wctzpb::Frame_TaggedTracesEntry_DoNotUse>(Arena*);
template<> ::wctzpb::Frame_TraceSummariesEntry_DoNotUse* Arena::CreateMaybeMessage<::wctzpb::Frame_TraceSummariesEntry_DoNotUse>(Arena*);
template<> ::wctzpb::IntArray* Arena::CreateMaybeMessage<::wctzpb::IntArray>(Arena*);
template<> ::wctzpb::Payload* Arena::CreateMaybeMessage<::wctzpb::Payload>(Arena*);
template<> ::wctzpb::Point* Arena::CreateMaybeMessage<::wctzpb::Point>(Arena*);
template<> ::wctzpb::Trace* Arena::CreateMaybeMessage<::wctzpb::Trace>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace wctzpb {

// ===================================================================

class Payload : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:wctzpb.Payload) */ {
 public:
  Payload();
  virtual ~Payload();

  Payload(const Payload& from);

  inline Payload& operator=(const Payload& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Payload(Payload&& from) noexcept
    : Payload() {
    *this = ::std::move(from);
  }

  inline Payload& operator=(Payload&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Payload& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Payload* internal_default_instance() {
    return reinterpret_cast<const Payload*>(
               &_Payload_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Payload* other);
  friend void swap(Payload& a, Payload& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Payload* New() const final {
    return CreateMaybeMessage<Payload>(NULL);
  }

  Payload* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Payload>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Payload& from);
  void MergeFrom(const Payload& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Payload* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .google.protobuf.Any objects = 1;
  int objects_size() const;
  void clear_objects();
  static const int kObjectsFieldNumber = 1;
  ::google::protobuf::Any* mutable_objects(int index);
  ::google::protobuf::RepeatedPtrField< ::google::protobuf::Any >*
      mutable_objects();
  const ::google::protobuf::Any& objects(int index) const;
  ::google::protobuf::Any* add_objects();
  const ::google::protobuf::RepeatedPtrField< ::google::protobuf::Any >&
      objects() const;

  // @@protoc_insertion_point(class_scope:wctzpb.Payload)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::google::protobuf::Any > objects_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_src_2fwctzpb_2eproto;
};
// -------------------------------------------------------------------

class Point : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:wctzpb.Point) */ {
 public:
  Point();
  virtual ~Point();

  Point(const Point& from);

  inline Point& operator=(const Point& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Point(Point&& from) noexcept
    : Point() {
    *this = ::std::move(from);
  }

  inline Point& operator=(Point&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Point& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Point* internal_default_instance() {
    return reinterpret_cast<const Point*>(
               &_Point_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Point* other);
  friend void swap(Point& a, Point& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Point* New() const final {
    return CreateMaybeMessage<Point>(NULL);
  }

  Point* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Point>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Point& from);
  void MergeFrom(const Point& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Point* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // float y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // float z = 3;
  void clear_z();
  static const int kZFieldNumber = 3;
  float z() const;
  void set_z(float value);

  // @@protoc_insertion_point(class_scope:wctzpb.Point)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  float x_;
  float y_;
  float z_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_src_2fwctzpb_2eproto;
};
// -------------------------------------------------------------------

class Depo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:wctzpb.Depo) */ {
 public:
  Depo();
  virtual ~Depo();

  Depo(const Depo& from);

  inline Depo& operator=(const Depo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Depo(Depo&& from) noexcept
    : Depo() {
    *this = ::std::move(from);
  }

  inline Depo& operator=(Depo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Depo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Depo* internal_default_instance() {
    return reinterpret_cast<const Depo*>(
               &_Depo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(Depo* other);
  friend void swap(Depo& a, Depo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Depo* New() const final {
    return CreateMaybeMessage<Depo>(NULL);
  }

  Depo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Depo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Depo& from);
  void MergeFrom(const Depo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Depo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .wctzpb.Point pos = 2;
  bool has_pos() const;
  void clear_pos();
  static const int kPosFieldNumber = 2;
  const ::wctzpb::Point& pos() const;
  ::wctzpb::Point* release_pos();
  ::wctzpb::Point* mutable_pos();
  void set_allocated_pos(::wctzpb::Point* pos);

  // uint64 ident = 1;
  void clear_ident();
  static const int kIdentFieldNumber = 1;
  ::google::protobuf::uint64 ident() const;
  void set_ident(::google::protobuf::uint64 value);

  // double time = 3;
  void clear_time();
  static const int kTimeFieldNumber = 3;
  double time() const;
  void set_time(double value);

  // double charge = 4;
  void clear_charge();
  static const int kChargeFieldNumber = 4;
  double charge() const;
  void set_charge(double value);

  // double energy = 5;
  void clear_energy();
  static const int kEnergyFieldNumber = 5;
  double energy() const;
  void set_energy(double value);

  // uint32 trackid = 6;
  void clear_trackid();
  static const int kTrackidFieldNumber = 6;
  ::google::protobuf::uint32 trackid() const;
  void set_trackid(::google::protobuf::uint32 value);

  // uint32 pdg = 7;
  void clear_pdg();
  static const int kPdgFieldNumber = 7;
  ::google::protobuf::uint32 pdg() const;
  void set_pdg(::google::protobuf::uint32 value);

  // uint64 prior = 8;
  void clear_prior();
  static const int kPriorFieldNumber = 8;
  ::google::protobuf::uint64 prior() const;
  void set_prior(::google::protobuf::uint64 value);

  // double extent_long = 9;
  void clear_extent_long();
  static const int kExtentLongFieldNumber = 9;
  double extent_long() const;
  void set_extent_long(double value);

  // double extent_tran = 10;
  void clear_extent_tran();
  static const int kExtentTranFieldNumber = 10;
  double extent_tran() const;
  void set_extent_tran(double value);

  // @@protoc_insertion_point(class_scope:wctzpb.Depo)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::wctzpb::Point* pos_;
  ::google::protobuf::uint64 ident_;
  double time_;
  double charge_;
  double energy_;
  ::google::protobuf::uint32 trackid_;
  ::google::protobuf::uint32 pdg_;
  ::google::protobuf::uint64 prior_;
  double extent_long_;
  double extent_tran_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_src_2fwctzpb_2eproto;
};
// -------------------------------------------------------------------

class DepoSet : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:wctzpb.DepoSet) */ {
 public:
  DepoSet();
  virtual ~DepoSet();

  DepoSet(const DepoSet& from);

  inline DepoSet& operator=(const DepoSet& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DepoSet(DepoSet&& from) noexcept
    : DepoSet() {
    *this = ::std::move(from);
  }

  inline DepoSet& operator=(DepoSet&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const DepoSet& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DepoSet* internal_default_instance() {
    return reinterpret_cast<const DepoSet*>(
               &_DepoSet_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(DepoSet* other);
  friend void swap(DepoSet& a, DepoSet& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DepoSet* New() const final {
    return CreateMaybeMessage<DepoSet>(NULL);
  }

  DepoSet* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DepoSet>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DepoSet& from);
  void MergeFrom(const DepoSet& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DepoSet* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .wctzpb.Depo depos = 2;
  int depos_size() const;
  void clear_depos();
  static const int kDeposFieldNumber = 2;
  ::wctzpb::Depo* mutable_depos(int index);
  ::google::protobuf::RepeatedPtrField< ::wctzpb::Depo >*
      mutable_depos();
  const ::wctzpb::Depo& depos(int index) const;
  ::wctzpb::Depo* add_depos();
  const ::google::protobuf::RepeatedPtrField< ::wctzpb::Depo >&
      depos() const;

  // uint32 ident = 1;
  void clear_ident();
  static const int kIdentFieldNumber = 1;
  ::google::protobuf::uint32 ident() const;
  void set_ident(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:wctzpb.DepoSet)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::wctzpb::Depo > depos_;
  ::google::protobuf::uint32 ident_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_src_2fwctzpb_2eproto;
};
// -------------------------------------------------------------------

class FloatArray : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:wctzpb.FloatArray) */ {
 public:
  FloatArray();
  virtual ~FloatArray();

  FloatArray(const FloatArray& from);

  inline FloatArray& operator=(const FloatArray& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  FloatArray(FloatArray&& from) noexcept
    : FloatArray() {
    *this = ::std::move(from);
  }

  inline FloatArray& operator=(FloatArray&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const FloatArray& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FloatArray* internal_default_instance() {
    return reinterpret_cast<const FloatArray*>(
               &_FloatArray_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(FloatArray* other);
  friend void swap(FloatArray& a, FloatArray& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline FloatArray* New() const final {
    return CreateMaybeMessage<FloatArray>(NULL);
  }

  FloatArray* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<FloatArray>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const FloatArray& from);
  void MergeFrom(const FloatArray& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FloatArray* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float elements = 1;
  int elements_size() const;
  void clear_elements();
  static const int kElementsFieldNumber = 1;
  float elements(int index) const;
  void set_elements(int index, float value);
  void add_elements(float value);
  const ::google::protobuf::RepeatedField< float >&
      elements() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_elements();

  // @@protoc_insertion_point(class_scope:wctzpb.FloatArray)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< float > elements_;
  mutable std::atomic<int> _elements_cached_byte_size_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_src_2fwctzpb_2eproto;
};
// -------------------------------------------------------------------

class IntArray : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:wctzpb.IntArray) */ {
 public:
  IntArray();
  virtual ~IntArray();

  IntArray(const IntArray& from);

  inline IntArray& operator=(const IntArray& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  IntArray(IntArray&& from) noexcept
    : IntArray() {
    *this = ::std::move(from);
  }

  inline IntArray& operator=(IntArray&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const IntArray& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const IntArray* internal_default_instance() {
    return reinterpret_cast<const IntArray*>(
               &_IntArray_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(IntArray* other);
  friend void swap(IntArray& a, IntArray& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline IntArray* New() const final {
    return CreateMaybeMessage<IntArray>(NULL);
  }

  IntArray* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<IntArray>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const IntArray& from);
  void MergeFrom(const IntArray& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IntArray* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 elements = 1;
  int elements_size() const;
  void clear_elements();
  static const int kElementsFieldNumber = 1;
  ::google::protobuf::int32 elements(int index) const;
  void set_elements(int index, ::google::protobuf::int32 value);
  void add_elements(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      elements() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_elements();

  // @@protoc_insertion_point(class_scope:wctzpb.IntArray)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > elements_;
  mutable std::atomic<int> _elements_cached_byte_size_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_src_2fwctzpb_2eproto;
};
// -------------------------------------------------------------------

class Trace : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:wctzpb.Trace) */ {
 public:
  Trace();
  virtual ~Trace();

  Trace(const Trace& from);

  inline Trace& operator=(const Trace& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Trace(Trace&& from) noexcept
    : Trace() {
    *this = ::std::move(from);
  }

  inline Trace& operator=(Trace&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Trace& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Trace* internal_default_instance() {
    return reinterpret_cast<const Trace*>(
               &_Trace_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(Trace* other);
  friend void swap(Trace& a, Trace& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Trace* New() const final {
    return CreateMaybeMessage<Trace>(NULL);
  }

  Trace* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Trace>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Trace& from);
  void MergeFrom(const Trace& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Trace* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .wctzpb.FloatArray samples = 3;
  bool has_samples() const;
  void clear_samples();
  static const int kSamplesFieldNumber = 3;
  const ::wctzpb::FloatArray& samples() const;
  ::wctzpb::FloatArray* release_samples();
  ::wctzpb::FloatArray* mutable_samples();
  void set_allocated_samples(::wctzpb::FloatArray* samples);

  // int32 channel = 1;
  void clear_channel();
  static const int kChannelFieldNumber = 1;
  ::google::protobuf::int32 channel() const;
  void set_channel(::google::protobuf::int32 value);

  // int32 tbin = 2;
  void clear_tbin();
  static const int kTbinFieldNumber = 2;
  ::google::protobuf::int32 tbin() const;
  void set_tbin(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:wctzpb.Trace)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::wctzpb::FloatArray* samples_;
  ::google::protobuf::int32 channel_;
  ::google::protobuf::int32 tbin_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_src_2fwctzpb_2eproto;
};
// -------------------------------------------------------------------

class BinRangeList : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:wctzpb.BinRangeList) */ {
 public:
  BinRangeList();
  virtual ~BinRangeList();

  BinRangeList(const BinRangeList& from);

  inline BinRangeList& operator=(const BinRangeList& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BinRangeList(BinRangeList&& from) noexcept
    : BinRangeList() {
    *this = ::std::move(from);
  }

  inline BinRangeList& operator=(BinRangeList&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const BinRangeList& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BinRangeList* internal_default_instance() {
    return reinterpret_cast<const BinRangeList*>(
               &_BinRangeList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  void Swap(BinRangeList* other);
  friend void swap(BinRangeList& a, BinRangeList& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BinRangeList* New() const final {
    return CreateMaybeMessage<BinRangeList>(NULL);
  }

  BinRangeList* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<BinRangeList>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const BinRangeList& from);
  void MergeFrom(const BinRangeList& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BinRangeList* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 beg = 1;
  int beg_size() const;
  void clear_beg();
  static const int kBegFieldNumber = 1;
  ::google::protobuf::int32 beg(int index) const;
  void set_beg(int index, ::google::protobuf::int32 value);
  void add_beg(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      beg() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_beg();

  // repeated int32 end = 2;
  int end_size() const;
  void clear_end();
  static const int kEndFieldNumber = 2;
  ::google::protobuf::int32 end(int index) const;
  void set_end(int index, ::google::protobuf::int32 value);
  void add_end(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      end() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_end();

  // @@protoc_insertion_point(class_scope:wctzpb.BinRangeList)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > beg_;
  mutable std::atomic<int> _beg_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > end_;
  mutable std::atomic<int> _end_cached_byte_size_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_src_2fwctzpb_2eproto;
};
// -------------------------------------------------------------------

class ChannelMasks_BinRangeListsEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<ChannelMasks_BinRangeListsEntry_DoNotUse, 
    ::google::protobuf::int32, ::wctzpb::BinRangeList,
    ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
static bool _ParseMap(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  typedef ::google::protobuf::internal::MapEntry<ChannelMasks_BinRangeListsEntry_DoNotUse, 
    ::google::protobuf::int32, ::wctzpb::BinRangeList,
    ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  ChannelMasks_BinRangeListsEntry_DoNotUse();
  ChannelMasks_BinRangeListsEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const ChannelMasks_BinRangeListsEntry_DoNotUse& other);
  static const ChannelMasks_BinRangeListsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const ChannelMasks_BinRangeListsEntry_DoNotUse*>(&_ChannelMasks_BinRangeListsEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class ChannelMasks : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:wctzpb.ChannelMasks) */ {
 public:
  ChannelMasks();
  virtual ~ChannelMasks();

  ChannelMasks(const ChannelMasks& from);

  inline ChannelMasks& operator=(const ChannelMasks& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ChannelMasks(ChannelMasks&& from) noexcept
    : ChannelMasks() {
    *this = ::std::move(from);
  }

  inline ChannelMasks& operator=(ChannelMasks&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ChannelMasks& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ChannelMasks* internal_default_instance() {
    return reinterpret_cast<const ChannelMasks*>(
               &_ChannelMasks_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  void Swap(ChannelMasks* other);
  friend void swap(ChannelMasks& a, ChannelMasks& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ChannelMasks* New() const final {
    return CreateMaybeMessage<ChannelMasks>(NULL);
  }

  ChannelMasks* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ChannelMasks>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ChannelMasks& from);
  void MergeFrom(const ChannelMasks& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ChannelMasks* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<int32, .wctzpb.BinRangeList> bin_range_lists = 1;
  int bin_range_lists_size() const;
  void clear_bin_range_lists();
  static const int kBinRangeListsFieldNumber = 1;
  const ::google::protobuf::Map< ::google::protobuf::int32, ::wctzpb::BinRangeList >&
      bin_range_lists() const;
  ::google::protobuf::Map< ::google::protobuf::int32, ::wctzpb::BinRangeList >*
      mutable_bin_range_lists();

  // @@protoc_insertion_point(class_scope:wctzpb.ChannelMasks)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::MapField<
      ChannelMasks_BinRangeListsEntry_DoNotUse,
      ::google::protobuf::int32, ::wctzpb::BinRangeList,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > bin_range_lists_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_src_2fwctzpb_2eproto;
};
// -------------------------------------------------------------------

class Frame_TaggedTracesEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<Frame_TaggedTracesEntry_DoNotUse, 
    ::std::string, ::wctzpb::IntArray,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
static bool _ParseMap(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  typedef ::google::protobuf::internal::MapEntry<Frame_TaggedTracesEntry_DoNotUse, 
    ::std::string, ::wctzpb::IntArray,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  Frame_TaggedTracesEntry_DoNotUse();
  Frame_TaggedTracesEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const Frame_TaggedTracesEntry_DoNotUse& other);
  static const Frame_TaggedTracesEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const Frame_TaggedTracesEntry_DoNotUse*>(&_Frame_TaggedTracesEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class Frame_TraceSummariesEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<Frame_TraceSummariesEntry_DoNotUse, 
    ::std::string, ::wctzpb::FloatArray,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
static bool _ParseMap(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  typedef ::google::protobuf::internal::MapEntry<Frame_TraceSummariesEntry_DoNotUse, 
    ::std::string, ::wctzpb::FloatArray,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  Frame_TraceSummariesEntry_DoNotUse();
  Frame_TraceSummariesEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const Frame_TraceSummariesEntry_DoNotUse& other);
  static const Frame_TraceSummariesEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const Frame_TraceSummariesEntry_DoNotUse*>(&_Frame_TraceSummariesEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class Frame_ChannelMasksEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<Frame_ChannelMasksEntry_DoNotUse, 
    ::std::string, ::wctzpb::ChannelMasks,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
static bool _ParseMap(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  typedef ::google::protobuf::internal::MapEntry<Frame_ChannelMasksEntry_DoNotUse, 
    ::std::string, ::wctzpb::ChannelMasks,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  Frame_ChannelMasksEntry_DoNotUse();
  Frame_ChannelMasksEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const Frame_ChannelMasksEntry_DoNotUse& other);
  static const Frame_ChannelMasksEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const Frame_ChannelMasksEntry_DoNotUse*>(&_Frame_ChannelMasksEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class Frame : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:wctzpb.Frame) */ {
 public:
  Frame();
  virtual ~Frame();

  Frame(const Frame& from);

  inline Frame& operator=(const Frame& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Frame(Frame&& from) noexcept
    : Frame() {
    *this = ::std::move(from);
  }

  inline Frame& operator=(Frame&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Frame& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Frame* internal_default_instance() {
    return reinterpret_cast<const Frame*>(
               &_Frame_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    13;

  void Swap(Frame* other);
  friend void swap(Frame& a, Frame& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Frame* New() const final {
    return CreateMaybeMessage<Frame>(NULL);
  }

  Frame* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Frame>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Frame& from);
  void MergeFrom(const Frame& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Frame* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // repeated .wctzpb.Trace traces = 4;
  int traces_size() const;
  void clear_traces();
  static const int kTracesFieldNumber = 4;
  ::wctzpb::Trace* mutable_traces(int index);
  ::google::protobuf::RepeatedPtrField< ::wctzpb::Trace >*
      mutable_traces();
  const ::wctzpb::Trace& traces(int index) const;
  ::wctzpb::Trace* add_traces();
  const ::google::protobuf::RepeatedPtrField< ::wctzpb::Trace >&
      traces() const;

  // repeated string frame_tags = 5;
  int frame_tags_size() const;
  void clear_frame_tags();
  static const int kFrameTagsFieldNumber = 5;
  const ::std::string& frame_tags(int index) const;
  ::std::string* mutable_frame_tags(int index);
  void set_frame_tags(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_frame_tags(int index, ::std::string&& value);
  #endif
  void set_frame_tags(int index, const char* value);
  void set_frame_tags(int index, const char* value, size_t size);
  ::std::string* add_frame_tags();
  void add_frame_tags(const ::std::string& value);
  #if LANG_CXX11
  void add_frame_tags(::std::string&& value);
  #endif
  void add_frame_tags(const char* value);
  void add_frame_tags(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField<::std::string>& frame_tags() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* mutable_frame_tags();

  // map<string, .wctzpb.IntArray> tagged_traces = 6;
  int tagged_traces_size() const;
  void clear_tagged_traces();
  static const int kTaggedTracesFieldNumber = 6;
  const ::google::protobuf::Map< ::std::string, ::wctzpb::IntArray >&
      tagged_traces() const;
  ::google::protobuf::Map< ::std::string, ::wctzpb::IntArray >*
      mutable_tagged_traces();

  // map<string, .wctzpb.FloatArray> trace_summaries = 7;
  int trace_summaries_size() const;
  void clear_trace_summaries();
  static const int kTraceSummariesFieldNumber = 7;
  const ::google::protobuf::Map< ::std::string, ::wctzpb::FloatArray >&
      trace_summaries() const;
  ::google::protobuf::Map< ::std::string, ::wctzpb::FloatArray >*
      mutable_trace_summaries();

  // map<string, .wctzpb.ChannelMasks> channel_masks = 8;
  int channel_masks_size() const;
  void clear_channel_masks();
  static const int kChannelMasksFieldNumber = 8;
  const ::google::protobuf::Map< ::std::string, ::wctzpb::ChannelMasks >&
      channel_masks() const;
  ::google::protobuf::Map< ::std::string, ::wctzpb::ChannelMasks >*
      mutable_channel_masks();

  // double time = 2;
  void clear_time();
  static const int kTimeFieldNumber = 2;
  double time() const;
  void set_time(double value);

  // double tick = 3;
  void clear_tick();
  static const int kTickFieldNumber = 3;
  double tick() const;
  void set_tick(double value);

  // int32 ident = 1;
  void clear_ident();
  static const int kIdentFieldNumber = 1;
  ::google::protobuf::int32 ident() const;
  void set_ident(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:wctzpb.Frame)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::wctzpb::Trace > traces_;
  ::google::protobuf::RepeatedPtrField<::std::string> frame_tags_;
  ::google::protobuf::internal::MapField<
      Frame_TaggedTracesEntry_DoNotUse,
      ::std::string, ::wctzpb::IntArray,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > tagged_traces_;
  ::google::protobuf::internal::MapField<
      Frame_TraceSummariesEntry_DoNotUse,
      ::std::string, ::wctzpb::FloatArray,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > trace_summaries_;
  ::google::protobuf::internal::MapField<
      Frame_ChannelMasksEntry_DoNotUse,
      ::std::string, ::wctzpb::ChannelMasks,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > channel_masks_;
  double time_;
  double tick_;
  ::google::protobuf::int32 ident_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_src_2fwctzpb_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Payload

// repeated .google.protobuf.Any objects = 1;
inline int Payload::objects_size() const {
  return objects_.size();
}
inline ::google::protobuf::Any* Payload::mutable_objects(int index) {
  // @@protoc_insertion_point(field_mutable:wctzpb.Payload.objects)
  return objects_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::google::protobuf::Any >*
Payload::mutable_objects() {
  // @@protoc_insertion_point(field_mutable_list:wctzpb.Payload.objects)
  return &objects_;
}
inline const ::google::protobuf::Any& Payload::objects(int index) const {
  // @@protoc_insertion_point(field_get:wctzpb.Payload.objects)
  return objects_.Get(index);
}
inline ::google::protobuf::Any* Payload::add_objects() {
  // @@protoc_insertion_point(field_add:wctzpb.Payload.objects)
  return objects_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::google::protobuf::Any >&
Payload::objects() const {
  // @@protoc_insertion_point(field_list:wctzpb.Payload.objects)
  return objects_;
}

// -------------------------------------------------------------------

// Point

// float x = 1;
inline void Point::clear_x() {
  x_ = 0;
}
inline float Point::x() const {
  // @@protoc_insertion_point(field_get:wctzpb.Point.x)
  return x_;
}
inline void Point::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:wctzpb.Point.x)
}

// float y = 2;
inline void Point::clear_y() {
  y_ = 0;
}
inline float Point::y() const {
  // @@protoc_insertion_point(field_get:wctzpb.Point.y)
  return y_;
}
inline void Point::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:wctzpb.Point.y)
}

// float z = 3;
inline void Point::clear_z() {
  z_ = 0;
}
inline float Point::z() const {
  // @@protoc_insertion_point(field_get:wctzpb.Point.z)
  return z_;
}
inline void Point::set_z(float value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:wctzpb.Point.z)
}

// -------------------------------------------------------------------

// Depo

// uint64 ident = 1;
inline void Depo::clear_ident() {
  ident_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Depo::ident() const {
  // @@protoc_insertion_point(field_get:wctzpb.Depo.ident)
  return ident_;
}
inline void Depo::set_ident(::google::protobuf::uint64 value) {
  
  ident_ = value;
  // @@protoc_insertion_point(field_set:wctzpb.Depo.ident)
}

// .wctzpb.Point pos = 2;
inline bool Depo::has_pos() const {
  return this != internal_default_instance() && pos_ != NULL;
}
inline void Depo::clear_pos() {
  if (GetArenaNoVirtual() == NULL && pos_ != NULL) {
    delete pos_;
  }
  pos_ = NULL;
}
inline const ::wctzpb::Point& Depo::pos() const {
  const ::wctzpb::Point* p = pos_;
  // @@protoc_insertion_point(field_get:wctzpb.Depo.pos)
  return p != NULL ? *p : *reinterpret_cast<const ::wctzpb::Point*>(
      &::wctzpb::_Point_default_instance_);
}
inline ::wctzpb::Point* Depo::release_pos() {
  // @@protoc_insertion_point(field_release:wctzpb.Depo.pos)
  
  ::wctzpb::Point* temp = pos_;
  pos_ = NULL;
  return temp;
}
inline ::wctzpb::Point* Depo::mutable_pos() {
  
  if (pos_ == NULL) {
    auto* p = CreateMaybeMessage<::wctzpb::Point>(GetArenaNoVirtual());
    pos_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wctzpb.Depo.pos)
  return pos_;
}
inline void Depo::set_allocated_pos(::wctzpb::Point* pos) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete pos_;
  }
  if (pos) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      pos = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, pos, submessage_arena);
    }
    
  } else {
    
  }
  pos_ = pos;
  // @@protoc_insertion_point(field_set_allocated:wctzpb.Depo.pos)
}

// double time = 3;
inline void Depo::clear_time() {
  time_ = 0;
}
inline double Depo::time() const {
  // @@protoc_insertion_point(field_get:wctzpb.Depo.time)
  return time_;
}
inline void Depo::set_time(double value) {
  
  time_ = value;
  // @@protoc_insertion_point(field_set:wctzpb.Depo.time)
}

// double charge = 4;
inline void Depo::clear_charge() {
  charge_ = 0;
}
inline double Depo::charge() const {
  // @@protoc_insertion_point(field_get:wctzpb.Depo.charge)
  return charge_;
}
inline void Depo::set_charge(double value) {
  
  charge_ = value;
  // @@protoc_insertion_point(field_set:wctzpb.Depo.charge)
}

// double energy = 5;
inline void Depo::clear_energy() {
  energy_ = 0;
}
inline double Depo::energy() const {
  // @@protoc_insertion_point(field_get:wctzpb.Depo.energy)
  return energy_;
}
inline void Depo::set_energy(double value) {
  
  energy_ = value;
  // @@protoc_insertion_point(field_set:wctzpb.Depo.energy)
}

// uint32 trackid = 6;
inline void Depo::clear_trackid() {
  trackid_ = 0u;
}
inline ::google::protobuf::uint32 Depo::trackid() const {
  // @@protoc_insertion_point(field_get:wctzpb.Depo.trackid)
  return trackid_;
}
inline void Depo::set_trackid(::google::protobuf::uint32 value) {
  
  trackid_ = value;
  // @@protoc_insertion_point(field_set:wctzpb.Depo.trackid)
}

// uint32 pdg = 7;
inline void Depo::clear_pdg() {
  pdg_ = 0u;
}
inline ::google::protobuf::uint32 Depo::pdg() const {
  // @@protoc_insertion_point(field_get:wctzpb.Depo.pdg)
  return pdg_;
}
inline void Depo::set_pdg(::google::protobuf::uint32 value) {
  
  pdg_ = value;
  // @@protoc_insertion_point(field_set:wctzpb.Depo.pdg)
}

// uint64 prior = 8;
inline void Depo::clear_prior() {
  prior_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Depo::prior() const {
  // @@protoc_insertion_point(field_get:wctzpb.Depo.prior)
  return prior_;
}
inline void Depo::set_prior(::google::protobuf::uint64 value) {
  
  prior_ = value;
  // @@protoc_insertion_point(field_set:wctzpb.Depo.prior)
}

// double extent_long = 9;
inline void Depo::clear_extent_long() {
  extent_long_ = 0;
}
inline double Depo::extent_long() const {
  // @@protoc_insertion_point(field_get:wctzpb.Depo.extent_long)
  return extent_long_;
}
inline void Depo::set_extent_long(double value) {
  
  extent_long_ = value;
  // @@protoc_insertion_point(field_set:wctzpb.Depo.extent_long)
}

// double extent_tran = 10;
inline void Depo::clear_extent_tran() {
  extent_tran_ = 0;
}
inline double Depo::extent_tran() const {
  // @@protoc_insertion_point(field_get:wctzpb.Depo.extent_tran)
  return extent_tran_;
}
inline void Depo::set_extent_tran(double value) {
  
  extent_tran_ = value;
  // @@protoc_insertion_point(field_set:wctzpb.Depo.extent_tran)
}

// -------------------------------------------------------------------

// DepoSet

// uint32 ident = 1;
inline void DepoSet::clear_ident() {
  ident_ = 0u;
}
inline ::google::protobuf::uint32 DepoSet::ident() const {
  // @@protoc_insertion_point(field_get:wctzpb.DepoSet.ident)
  return ident_;
}
inline void DepoSet::set_ident(::google::protobuf::uint32 value) {
  
  ident_ = value;
  // @@protoc_insertion_point(field_set:wctzpb.DepoSet.ident)
}

// repeated .wctzpb.Depo depos = 2;
inline int DepoSet::depos_size() const {
  return depos_.size();
}
inline void DepoSet::clear_depos() {
  depos_.Clear();
}
inline ::wctzpb::Depo* DepoSet::mutable_depos(int index) {
  // @@protoc_insertion_point(field_mutable:wctzpb.DepoSet.depos)
  return depos_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::wctzpb::Depo >*
DepoSet::mutable_depos() {
  // @@protoc_insertion_point(field_mutable_list:wctzpb.DepoSet.depos)
  return &depos_;
}
inline const ::wctzpb::Depo& DepoSet::depos(int index) const {
  // @@protoc_insertion_point(field_get:wctzpb.DepoSet.depos)
  return depos_.Get(index);
}
inline ::wctzpb::Depo* DepoSet::add_depos() {
  // @@protoc_insertion_point(field_add:wctzpb.DepoSet.depos)
  return depos_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::wctzpb::Depo >&
DepoSet::depos() const {
  // @@protoc_insertion_point(field_list:wctzpb.DepoSet.depos)
  return depos_;
}

// -------------------------------------------------------------------

// FloatArray

// repeated float elements = 1;
inline int FloatArray::elements_size() const {
  return elements_.size();
}
inline void FloatArray::clear_elements() {
  elements_.Clear();
}
inline float FloatArray::elements(int index) const {
  // @@protoc_insertion_point(field_get:wctzpb.FloatArray.elements)
  return elements_.Get(index);
}
inline void FloatArray::set_elements(int index, float value) {
  elements_.Set(index, value);
  // @@protoc_insertion_point(field_set:wctzpb.FloatArray.elements)
}
inline void FloatArray::add_elements(float value) {
  elements_.Add(value);
  // @@protoc_insertion_point(field_add:wctzpb.FloatArray.elements)
}
inline const ::google::protobuf::RepeatedField< float >&
FloatArray::elements() const {
  // @@protoc_insertion_point(field_list:wctzpb.FloatArray.elements)
  return elements_;
}
inline ::google::protobuf::RepeatedField< float >*
FloatArray::mutable_elements() {
  // @@protoc_insertion_point(field_mutable_list:wctzpb.FloatArray.elements)
  return &elements_;
}

// -------------------------------------------------------------------

// IntArray

// repeated int32 elements = 1;
inline int IntArray::elements_size() const {
  return elements_.size();
}
inline void IntArray::clear_elements() {
  elements_.Clear();
}
inline ::google::protobuf::int32 IntArray::elements(int index) const {
  // @@protoc_insertion_point(field_get:wctzpb.IntArray.elements)
  return elements_.Get(index);
}
inline void IntArray::set_elements(int index, ::google::protobuf::int32 value) {
  elements_.Set(index, value);
  // @@protoc_insertion_point(field_set:wctzpb.IntArray.elements)
}
inline void IntArray::add_elements(::google::protobuf::int32 value) {
  elements_.Add(value);
  // @@protoc_insertion_point(field_add:wctzpb.IntArray.elements)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
IntArray::elements() const {
  // @@protoc_insertion_point(field_list:wctzpb.IntArray.elements)
  return elements_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
IntArray::mutable_elements() {
  // @@protoc_insertion_point(field_mutable_list:wctzpb.IntArray.elements)
  return &elements_;
}

// -------------------------------------------------------------------

// Trace

// int32 channel = 1;
inline void Trace::clear_channel() {
  channel_ = 0;
}
inline ::google::protobuf::int32 Trace::channel() const {
  // @@protoc_insertion_point(field_get:wctzpb.Trace.channel)
  return channel_;
}
inline void Trace::set_channel(::google::protobuf::int32 value) {
  
  channel_ = value;
  // @@protoc_insertion_point(field_set:wctzpb.Trace.channel)
}

// int32 tbin = 2;
inline void Trace::clear_tbin() {
  tbin_ = 0;
}
inline ::google::protobuf::int32 Trace::tbin() const {
  // @@protoc_insertion_point(field_get:wctzpb.Trace.tbin)
  return tbin_;
}
inline void Trace::set_tbin(::google::protobuf::int32 value) {
  
  tbin_ = value;
  // @@protoc_insertion_point(field_set:wctzpb.Trace.tbin)
}

// .wctzpb.FloatArray samples = 3;
inline bool Trace::has_samples() const {
  return this != internal_default_instance() && samples_ != NULL;
}
inline void Trace::clear_samples() {
  if (GetArenaNoVirtual() == NULL && samples_ != NULL) {
    delete samples_;
  }
  samples_ = NULL;
}
inline const ::wctzpb::FloatArray& Trace::samples() const {
  const ::wctzpb::FloatArray* p = samples_;
  // @@protoc_insertion_point(field_get:wctzpb.Trace.samples)
  return p != NULL ? *p : *reinterpret_cast<const ::wctzpb::FloatArray*>(
      &::wctzpb::_FloatArray_default_instance_);
}
inline ::wctzpb::FloatArray* Trace::release_samples() {
  // @@protoc_insertion_point(field_release:wctzpb.Trace.samples)
  
  ::wctzpb::FloatArray* temp = samples_;
  samples_ = NULL;
  return temp;
}
inline ::wctzpb::FloatArray* Trace::mutable_samples() {
  
  if (samples_ == NULL) {
    auto* p = CreateMaybeMessage<::wctzpb::FloatArray>(GetArenaNoVirtual());
    samples_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wctzpb.Trace.samples)
  return samples_;
}
inline void Trace::set_allocated_samples(::wctzpb::FloatArray* samples) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete samples_;
  }
  if (samples) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      samples = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, samples, submessage_arena);
    }
    
  } else {
    
  }
  samples_ = samples;
  // @@protoc_insertion_point(field_set_allocated:wctzpb.Trace.samples)
}

// -------------------------------------------------------------------

// BinRangeList

// repeated int32 beg = 1;
inline int BinRangeList::beg_size() const {
  return beg_.size();
}
inline void BinRangeList::clear_beg() {
  beg_.Clear();
}
inline ::google::protobuf::int32 BinRangeList::beg(int index) const {
  // @@protoc_insertion_point(field_get:wctzpb.BinRangeList.beg)
  return beg_.Get(index);
}
inline void BinRangeList::set_beg(int index, ::google::protobuf::int32 value) {
  beg_.Set(index, value);
  // @@protoc_insertion_point(field_set:wctzpb.BinRangeList.beg)
}
inline void BinRangeList::add_beg(::google::protobuf::int32 value) {
  beg_.Add(value);
  // @@protoc_insertion_point(field_add:wctzpb.BinRangeList.beg)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
BinRangeList::beg() const {
  // @@protoc_insertion_point(field_list:wctzpb.BinRangeList.beg)
  return beg_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
BinRangeList::mutable_beg() {
  // @@protoc_insertion_point(field_mutable_list:wctzpb.BinRangeList.beg)
  return &beg_;
}

// repeated int32 end = 2;
inline int BinRangeList::end_size() const {
  return end_.size();
}
inline void BinRangeList::clear_end() {
  end_.Clear();
}
inline ::google::protobuf::int32 BinRangeList::end(int index) const {
  // @@protoc_insertion_point(field_get:wctzpb.BinRangeList.end)
  return end_.Get(index);
}
inline void BinRangeList::set_end(int index, ::google::protobuf::int32 value) {
  end_.Set(index, value);
  // @@protoc_insertion_point(field_set:wctzpb.BinRangeList.end)
}
inline void BinRangeList::add_end(::google::protobuf::int32 value) {
  end_.Add(value);
  // @@protoc_insertion_point(field_add:wctzpb.BinRangeList.end)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
BinRangeList::end() const {
  // @@protoc_insertion_point(field_list:wctzpb.BinRangeList.end)
  return end_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
BinRangeList::mutable_end() {
  // @@protoc_insertion_point(field_mutable_list:wctzpb.BinRangeList.end)
  return &end_;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// ChannelMasks

// map<int32, .wctzpb.BinRangeList> bin_range_lists = 1;
inline int ChannelMasks::bin_range_lists_size() const {
  return bin_range_lists_.size();
}
inline void ChannelMasks::clear_bin_range_lists() {
  bin_range_lists_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, ::wctzpb::BinRangeList >&
ChannelMasks::bin_range_lists() const {
  // @@protoc_insertion_point(field_map:wctzpb.ChannelMasks.bin_range_lists)
  return bin_range_lists_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, ::wctzpb::BinRangeList >*
ChannelMasks::mutable_bin_range_lists() {
  // @@protoc_insertion_point(field_mutable_map:wctzpb.ChannelMasks.bin_range_lists)
  return bin_range_lists_.MutableMap();
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// Frame

// int32 ident = 1;
inline void Frame::clear_ident() {
  ident_ = 0;
}
inline ::google::protobuf::int32 Frame::ident() const {
  // @@protoc_insertion_point(field_get:wctzpb.Frame.ident)
  return ident_;
}
inline void Frame::set_ident(::google::protobuf::int32 value) {
  
  ident_ = value;
  // @@protoc_insertion_point(field_set:wctzpb.Frame.ident)
}

// double time = 2;
inline void Frame::clear_time() {
  time_ = 0;
}
inline double Frame::time() const {
  // @@protoc_insertion_point(field_get:wctzpb.Frame.time)
  return time_;
}
inline void Frame::set_time(double value) {
  
  time_ = value;
  // @@protoc_insertion_point(field_set:wctzpb.Frame.time)
}

// double tick = 3;
inline void Frame::clear_tick() {
  tick_ = 0;
}
inline double Frame::tick() const {
  // @@protoc_insertion_point(field_get:wctzpb.Frame.tick)
  return tick_;
}
inline void Frame::set_tick(double value) {
  
  tick_ = value;
  // @@protoc_insertion_point(field_set:wctzpb.Frame.tick)
}

// repeated .wctzpb.Trace traces = 4;
inline int Frame::traces_size() const {
  return traces_.size();
}
inline void Frame::clear_traces() {
  traces_.Clear();
}
inline ::wctzpb::Trace* Frame::mutable_traces(int index) {
  // @@protoc_insertion_point(field_mutable:wctzpb.Frame.traces)
  return traces_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::wctzpb::Trace >*
Frame::mutable_traces() {
  // @@protoc_insertion_point(field_mutable_list:wctzpb.Frame.traces)
  return &traces_;
}
inline const ::wctzpb::Trace& Frame::traces(int index) const {
  // @@protoc_insertion_point(field_get:wctzpb.Frame.traces)
  return traces_.Get(index);
}
inline ::wctzpb::Trace* Frame::add_traces() {
  // @@protoc_insertion_point(field_add:wctzpb.Frame.traces)
  return traces_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::wctzpb::Trace >&
Frame::traces() const {
  // @@protoc_insertion_point(field_list:wctzpb.Frame.traces)
  return traces_;
}

// repeated string frame_tags = 5;
inline int Frame::frame_tags_size() const {
  return frame_tags_.size();
}
inline void Frame::clear_frame_tags() {
  frame_tags_.Clear();
}
inline const ::std::string& Frame::frame_tags(int index) const {
  // @@protoc_insertion_point(field_get:wctzpb.Frame.frame_tags)
  return frame_tags_.Get(index);
}
inline ::std::string* Frame::mutable_frame_tags(int index) {
  // @@protoc_insertion_point(field_mutable:wctzpb.Frame.frame_tags)
  return frame_tags_.Mutable(index);
}
inline void Frame::set_frame_tags(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:wctzpb.Frame.frame_tags)
  frame_tags_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void Frame::set_frame_tags(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:wctzpb.Frame.frame_tags)
  frame_tags_.Mutable(index)->assign(std::move(value));
}
#endif
inline void Frame::set_frame_tags(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  frame_tags_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:wctzpb.Frame.frame_tags)
}
inline void Frame::set_frame_tags(int index, const char* value, size_t size) {
  frame_tags_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:wctzpb.Frame.frame_tags)
}
inline ::std::string* Frame::add_frame_tags() {
  // @@protoc_insertion_point(field_add_mutable:wctzpb.Frame.frame_tags)
  return frame_tags_.Add();
}
inline void Frame::add_frame_tags(const ::std::string& value) {
  frame_tags_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:wctzpb.Frame.frame_tags)
}
#if LANG_CXX11
inline void Frame::add_frame_tags(::std::string&& value) {
  frame_tags_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:wctzpb.Frame.frame_tags)
}
#endif
inline void Frame::add_frame_tags(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  frame_tags_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:wctzpb.Frame.frame_tags)
}
inline void Frame::add_frame_tags(const char* value, size_t size) {
  frame_tags_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:wctzpb.Frame.frame_tags)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
Frame::frame_tags() const {
  // @@protoc_insertion_point(field_list:wctzpb.Frame.frame_tags)
  return frame_tags_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>*
Frame::mutable_frame_tags() {
  // @@protoc_insertion_point(field_mutable_list:wctzpb.Frame.frame_tags)
  return &frame_tags_;
}

// map<string, .wctzpb.IntArray> tagged_traces = 6;
inline int Frame::tagged_traces_size() const {
  return tagged_traces_.size();
}
inline void Frame::clear_tagged_traces() {
  tagged_traces_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::wctzpb::IntArray >&
Frame::tagged_traces() const {
  // @@protoc_insertion_point(field_map:wctzpb.Frame.tagged_traces)
  return tagged_traces_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::wctzpb::IntArray >*
Frame::mutable_tagged_traces() {
  // @@protoc_insertion_point(field_mutable_map:wctzpb.Frame.tagged_traces)
  return tagged_traces_.MutableMap();
}

// map<string, .wctzpb.FloatArray> trace_summaries = 7;
inline int Frame::trace_summaries_size() const {
  return trace_summaries_.size();
}
inline void Frame::clear_trace_summaries() {
  trace_summaries_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::wctzpb::FloatArray >&
Frame::trace_summaries() const {
  // @@protoc_insertion_point(field_map:wctzpb.Frame.trace_summaries)
  return trace_summaries_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::wctzpb::FloatArray >*
Frame::mutable_trace_summaries() {
  // @@protoc_insertion_point(field_mutable_map:wctzpb.Frame.trace_summaries)
  return trace_summaries_.MutableMap();
}

// map<string, .wctzpb.ChannelMasks> channel_masks = 8;
inline int Frame::channel_masks_size() const {
  return channel_masks_.size();
}
inline void Frame::clear_channel_masks() {
  channel_masks_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::wctzpb::ChannelMasks >&
Frame::channel_masks() const {
  // @@protoc_insertion_point(field_map:wctzpb.Frame.channel_masks)
  return channel_masks_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::wctzpb::ChannelMasks >*
Frame::mutable_channel_masks() {
  // @@protoc_insertion_point(field_mutable_map:wctzpb.Frame.channel_masks)
  return channel_masks_.MutableMap();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace wctzpb

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_src_2fwctzpb_2eproto
